spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092

    # Producer behavior
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        "[enable.idempotence]": true
        "[spring.json.add.type.headers]": false
